
version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: greenweez sales - each row represents specific product(s) sold for each order_id
        columns:
          - name: date_date
            description: the date of the sale
          - name: orders_id
            description: the order id which contains 1 or more products
          - name: products_id
            description: one or more of a specific product sold per order_id
          - name: revenue
            description: the turnover per product
          - name: quantity
            description: the quantity of product sold per order_id
      - name: product
        identifier: raw_gz_product
        description: greenweez product info - each row represents one (and only one) product and the purchase price for item
        columns:
          - name: products_id
            description: unique identifier for specific greenweez product
          - name: purchase_price
            description: greenweez purchase price of specified product
      - name: ship
        identifier: raw_gz_ship
        description: greenweez shipping info - each row represents shipping cost/revenue for one order
        columns:
          - name: orders_id
            description: unique identifier of order for which row describes shipping cost/revenue
          - name: shipping_fee
            description: how much customer is charged for greenweez to ship order
          - name: log_cost
            description: how much greenweez pays for order logging
          - name: ship_cost
            description: how much greenweez pays for order shipping